name: Close Stale issues and PRs

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 3
          stale-issue-message: 'Inactive in 30 days. 30 天沒有動靜。'
          stale-pr-message: 'Inactive in 30 days. 30 天沒有動靜。'
          close-issue-message: 'Close inactive issue. 關閉不活躍 issue 。'
          close-pr-message: 'Close inactive PR. 關閉不活躍 PR 。'
          only-labels: question,invalid
